### ISSUE TITLE
How do you create a JWT Token?

### ISSUE THREAD

**Issue by KaliPete** [Makhuta/homeassistant-duolingo#1]
It seems it's mandatory, but I'm not having any luck working out how one does this. 
(question also active in the HomeAssistant Discord too: https://discord.com/channels/330944238910963714/1286292795631603734 )

**Comment by Makhuta** [comment]
Oh, sorry I forgot to mention it in the README. I will fix it as soon as possible.

If I remember correctly it can ve found somewhere in browser memory when logged into your account but I can't remember where right now. After I fix the README it should contain command that you will run in the browser console and it will give you the token, also there will be example for it.

Thanks for bringing this to my attention.
