### ISSUE TITLE
Add in which League user is

### ISSUE THREAD

**Issue by jandechent** [Makhuta/homeassistant-duolingo#6]
Not sure if the API allows this, but the leaderboard could be amended by the league the user is in.

**Comment by Makhuta** [comment]
Should be added in the latest version [v0.2.10](https://github.com/Makhuta/homeassistant-duolingo/releases/tag/v0.2.10) you can check it out. The HACS should give you notification that there is a update for it in aprox. 20 hours.

**Comment by Makhuta** [comment]
I suppose that it works as you requested. So I will close as resolved.
